### PR TITLE
Added Kadane's Algorithm

### PR DESCRIPTION
**Pull request by rsarthak**

### CODE REVIEW

**Comment by spiderxp3** [comment]
Can you also add some pictures related to it for more explanation.

**Comment by spiderxp3** [comment]
and also add its complexity.

**Comment by rsarthak** [comment]
I'll add

**Comment by spiderxp3** [comment]
Try to add working algo and code inside a box to give it a professional look.

**Comment by rsarthak** [comment]
Ok, I'll do it.

**Comment by spiderxp3** [comment]
Great

**Pull request merged**
